```mermaid
classDiagram
    PizzaOrder "1" --> "*" PizzaAmount : RequestedOrder
    PizzaRecipeDto "1" --> "*" StockDto : Ingredients
    
    class PizzaOrder {
        +RequestedOrder: ComparableList~PizzaAmount~
    }
    
    class PizzaAmount {
        +PizzaType: PizzaRecipeType
        +Amount: ushort
    }
    
    class PizzaRecipeDto {
        +RecipeType: PizzaRecipeType
        +Ingredients: ComparableList~StockDto~
        +Price: int
        +Id: long
    }
    
    class StockDto {
        +StockType: StockType
        +Amount: int
        +Id: long
    }

    class PizzaRecipeType {
        <<enum>>
        StandardPizza
        ExtremelyTastyPizza
        OddPizza
        RarePizza
        HorseRadishPizza
        EmptyPizza
    }
    
    class StockType {
        <<enum>>
        Dough
        Tomatoes
        GratedCheese
        GenericSpices
        FermentedDough
        RottenTomatoes
        UngenericSpices
        Bacon
    }
```
